server:
  port: 8080
  servlet:
    context-path: /

spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.92.157.62:3326/vue?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password: Nej6FLcVKcaTKK-

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.se.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    com.example.se: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %-5level - %msg%n'
  file:
    name: logs/app.log